### ISSUE TITLE
EntityLinq with Func<> as a parameter works only once

### ISSUE THREAD

**Issue by Ignatella** [streamx-co/try.elinq#9] opened 2021-03-30 08:32 UTC
### Problem:
While using EntityLinq with PostgreSql and Func<> as a parameter for WHERE i faced the problem, that first query is working just as i want, but all another, after that first, does not update actionId and all the time function returns the same output.

`(act) => act.StageActionId == stageActionId acts as stageActionId` is the same for any further requests.

### Code snippet:
```c#
 public async Task<StageAction> GetActionByIdAsync(string stageActionId)
        {
            var actions = await GetStageActions((act) => act.StageActionId == stageActionId).AsNoTracking().ToListAsync();
            return actions.Where(a => a.ParentAction == null).FirstOrDefault();
        }


private IQueryable<StageAction> GetStageActions(Func<StageAction, bool> rootWhere)
        {
            var query = _context.StageActions.Query(() =>
            {
                var subQuery = SubQuery((StageAction rootActions, StageAction childActions) =>
                {
                    var r = SELECT(rootActions);
                    FROM(rootActions);
                    WHERE(rootWhere(rootActions));

                    UNION_ALL();

                    var act = r.Current();

                    SELECT(childActions);
                    FROM(childActions).JOIN(act).ON(childActions.ParentActionId == act.StageActionId);

                    return r;
                });

                WITH(RECURSIVE(subQuery));

                var result = SELECT(subQuery);
                FROM(subQuery);

                return result;
            });

            return query.AsNoTracking().Include(a => a.ChildActions).Include(a => a.ActionData);
        }

```

### EF Core output [for all 2+ requests parameter p0 is the same]:
```sql
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (3ms) [Parameters=[p0='ee20c449-7312-4c56-a48b-bb82e9e56010'], CommandType='Text', CommandTimeout='30']
SELECT s."StageActionId", s."ByAdmin", s."CreatedAt", s."EventStageId", s."ParentActionId", s."Type", s0."StageActionId", s0."ByAdmin", s0."CreatedAt", s0."EventStageId", s0."ParentActionId", s0."Type", s1."ActionDataId", s1."Key", s1."StageActionId", s1."Value"
FROM (
    WITH RECURSIVE q0  AS 
    (SELECT t0.*
    FROM "StageActions" AS t0
    WHERE (t0."StageActionId" = @p0)
    UNION ALL
    SELECT t1.*
    FROM "StageActions" AS t1  INNER JOIN q0 AS t2  ON (t1."ParentActionId" = t2."StageActionId"))
    SELECT q0.*
    FROM q0
) AS s
LEFT JOIN "StageActions" AS s0 ON s."StageActionId" = s0."ParentActionId"
LEFT JOIN "StageActionData" AS s1 ON s."StageActionId" = s1."StageActionId"
ORDER BY s."StageActionId", s0."StageActionId", s1."ActionDataId"
```

### What i have already tried:

1) Try AsNoTracking() because i was thinking caching can be the problem.
2) Try to not to send Func<> as a parameter but by the class field.
3) If i implement the Func<> in WHERE() func it works as expected. Means: WHERE(rootActions.StageActionId == stageActionId) and stageActionId is being sent as a parameter for GetStageActions().
4) Try to pass `Expression<Func<StageAction, bool>>() whereRoot` as a parameter and then use `whereRoot.Compile().Invoke(...)`
but then it throws an [error](https://ibb.co/WH4HthR)
### Why i wanna implement this:
I have some functions(all differs only by WHERE()) and wanna centralize logic but not to write the same code multiple times.

### Thank You! 
P.S. Love elinq

**Comment by kostat** [comment] 2021-06-21 13:06
Thank you very much for the bug report and warm words!
The issue is fixed in the [last release](https://www.nuget.org/packages/Streamx.Linq.SQL.EFCore/)

**Closed by kostat** 2021-06-21 13:06 UTC
